image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    branches: true

ports:
- port: 3000
  onOpen: ignore
# We open this port because it's the port that nginx is serving and which is federating the other services (web app and chain in this case)
- port: 8000
  onOpen: open-preview
- port: 8080
  onOpen: ignore
- port: 8888
  onOpen: ignore
- port: 9876
  onOpen: ignore

tasks:
- name: WebApp
  init: chmod +x $PWD/eosio/scripts/replaceUrlInAppManifest.sh
  # init: $PWD/eosio/scripts/replaceUrlInAppManifest.sh
  # init: yarn
  # command: alias ls='ls -al --color'
  # We need the $PWD here because this path is not resolved from the current folder but from the path nginx runs from.  $PWD is the workspace path where the copy of the repo files is
  # command: nginx -c $PWD/nginx.conf; yarn start
  command: ls -al --color $PWD/eosio/scripts
- name: Blockchain
  init: chmod +x $PWD/eosio/scripts/deploy_contracts.sh
  # before: cleos wallet unlock --password </password
  # command: nodeos --config-dir ~/eosio/chain/config --data-dir ~/eosio/chain/data -e -p eosio --plugin eosio::chain_api_plugin --contracts-console
- name: Init Blockchain
  # init: $PWD/eosio/scripts/deploy_contracts.sh